stages:
  - build
  - run

build_image:
  stage: build
  script:
    - docker build -t ml-training-image .
    - docker images
  rules:
    - changes:
        - images/**/*

run_container:
  stage: run
  script:
    - docker run -v $(pwd)/exports:/app/exports ml-training-image
  rules:
    - changes:
        - images/**/*
